### PR TITLE
repl: print multiple values, save *, **, *** and all

### PR DESCRIPTION
**Pull request by vindarel**
Hi,

Here we catch all returned values from EVAL and we print them on multiple lines. We save the special variables `*` and all (which are already part of the CL-USER package).

Now this works:

    (values 1 2 3)
    *
    ++
    ///

### CODE REVIEW

**Review by hellerve — APPROVED** [review]
Looks great!

**Comment by hellerve** [comment]
This is great! Would you be able to also update the README where `*last-result*` is mentioned?

**Comment by vindarel** [comment]
updated the readme.

**Comment by hellerve** [comment]
Perfect, thank you!

**Pull request merged**
